#!/bin/bash

set -ex

if [[ $(uname -r) =~ "arch" ]]; then
  if command -v yay; then
    yay -Sy -a --answerdiff N --answerclean A --needed --noconfirm --quiet \
      nerd-fonts-cascadia-code
  fi
fi
