k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 500
    buffer: 5000
    sinceSeconds: -1
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: arn:aws:eks:eu-west-1:089720790877:cluster/bb1
  currentCluster: arn:aws:eks:eu-west-1:089720790877:cluster/bb1
  clusters:
    arn:aws:eks:eu-west-1:089720790877:cluster/bb1:
      namespace:
        active: ""
        favorites:
        - loki
        - cortex
        - sre-tools
        - argocd
        - monitoring
        - all
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:eu-west-1:089720790877:cluster/cw1:
      namespace:
        active: default
        favorites:
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:eu-west-1:569903310786:cluster/eu-prod1:
      namespace:
        active: ""
        favorites:
        - shared-services
        - kube-system
        - all
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:us-east-2:089720790877:cluster/sh1:
      namespace:
        active: ""
        favorites:
        - all
        - default
      view:
        active: app
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:us-east-2:089720790877:cluster/us-dev1:
      namespace:
        active: portal
        favorites:
        - portal
        - monitoring
        - omni
        - mdp
        - all
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:us-east-2:569903310786:cluster/us-prod1:
      namespace:
        active: portal
        favorites:
        - applied-innovation
        - monitoring
        - portal
        - all
        - kube-system
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:us-east-2:586787430666:cluster/us-qa1:
      namespace:
        active: ""
        favorites:
        - gnpd
        - applied-innovation
        - monitoring
        - portal
        - argocd
        - omni
        - kube-system
        - all
        - image-service
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_mntl-gke-dev-r40p_europe-west1_cw1:
      namespace:
        active: portal
        favorites:
        - all
        - portal
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_mntl-gke-prod-5evh_europe-west1_eu-prod1:
      namespace:
        active: portal
        favorites:
        - all
        - flux-apps
        - portal
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
