#!/bin/bash

PARAMS=""
while (( "$#" )); do
  case "$1" in
    -n|--namespace)
      if [ -n "$2" ] && [ "${2:0:1}" != "-" ]; then
        NAMESPACE=$2
        shift 2
      else
        echo "Error: Argument for $1 is missing" >&2
        exit 1
      fi
      ;;
    -?|--?=) # unsupported flags
      echo "Error: Unsupported flag $1" >&2
      exit 1
      ;;
    *) # preserve positional arguments
      PARAMS="$PARAMS $1"
      shift
      ;;
  esac
done
# set positional arguments in their proper place
eval set -- "$PARAMS"

if [[ "${#PARAMS[@]}" -eq 0 ]]; then
  echo "secret name must be provided"
  exit 1
fi

NAMESPACE=${NAMESPACE:-default}
SECRET_NAME="$1"
KEY_NAME="$2"

json=$(kubectl get secret -n "$NAMESPACE" "$SECRET_NAME" -ojson)
if [[ -z "$KEY_NAME" ]]; then
  echo "$json" | jq -r ".data | keys[]"
else
  echo "$json" | jq -r ".data[\"$KEY_NAME\"]" | base64 -d -i
fi
