#!/bin/bash

set -e

BACKGROUND="/home/bbrockway/wallpaper/dolomites.jpg"


function reload_polybar() {
  if pgrep -x polybar; then
    pkill -x polybar
    while pgrep -x polybar; do
      sleep 0.5
    done
  fi
  if type "xrandr"; then
    for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
      MONITOR=$m polybar --reload taskbar &
      sleep 0.5
    done
  else
    polybar --reload taskbar &
  fi
}

function reload_feh() {
  feh --bg-scale "$BACKGROUND"
}

function reload_qtile() {
  qtile cmd-obj -o cmd -f reload_config
}

reload_polybar
reload_feh
#sleep 5
#reload_qtile
